### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by kvmanohar22** [krssg-ssl/tactics_py#1]
Comment the tactic which you are working on right now and the ones you will work on.

- [ ] TGoalie
- [ ] TGoToBall
- [ ] TGoToPoint
- [ ] TPosition
- [ ] TReceive
- [ ] TDribbleTurnPass
- [ ] TIntercept
- [ ] TMark
- [ ] TPassToPoint  (to be named TAttacker)
- [ ] TKickToGoal
- [ ] TStop
- [ ] TDefendArc (changes to be made)
- [ ] TAttackSupportWing (changes to be made)
- [ ] TAttackSupportCenter (changes to be made)

Discuss and write tactics.
Think more new tactics.

**Comment by kvmanohar22** [comment]
I think we need to have one more data element in each tactic which tracks the duration of every tactic instance. This makes sure that the tactic will **end** for sure. Any thoughts @MayankB11 @annimesh2809 @RishitSinha ?

**Comment by kvmanohar22** [comment]
Completed TStop tactic

**Comment by MayankB11** [comment]
@ashishkg0022 @americast @sipah00 @Mul16

**Comment by sipah00** [comment]
I will work on tIntercept tactic for now.

**Comment by ashishkg0022** [comment]
i wiil work on tPassToPoint

**Comment by americast** [comment]
@MayankB11 I would like to work on `tKickToGoal`

**Comment by ashishkg0022** [comment]
I will work tDribbleTurnPass

**Comment by MuLx10** [comment]
working on tGoalie

**Comment by ashishkg0022** [comment]
will work on tAttackSupport1_Center

**Comment by Mul16** [comment]
test pending for tGoalie
Working on tPassToPoint

**Comment by MuLx10** [comment]
test pending :  `tGoalie`
Working on  `tDefendARC`

**Comment by americast** [comment]
test pending: `tKickToGoal`
Would like to work on: `tPosition`
ping @MayankB11

**Comment by ashishkg0022** [comment]
@americast tposition is written previously

**Comment by americast** [comment]
@ashishkg0022 @MayankB11 Cool! I'll work on `tReceive`

**Comment by sipah00** [comment]
I am working on tAttackSupport1_Wing , tGoToBall and tmark.

**Comment by MuLx10** [comment]
[WIP] `tDefendARC`
working on` tDefendARC_left`, `tDefendARC_right`
